### ISSUE TITLE
netlify dev --live error - "missing release version"

### ISSUE THREAD

**Issue by sw-yx** [netlify/netlify-dev-plugin#154]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
https://twitter.com/amacarthur/status/1120736679218827266

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**

**- Please mention your node.js, and operating system version.**

**Comment by sw-yx** [comment]
from @calavera:

> it looks like this is not being set: https://github.com/netlify/gh-release-fetch/blob/master/src/index.ts#L15

**Comment by calavera** [comment]
We need more information about that environment. If that was not working at all, the live flag would not work for anyone at all.

**Comment by alexmacarthur** [comment]
@calavera I hit this bug working with a couple of different repositories, including my Gatsby site: 

https://github.com/alexmacarthur/macarthur-me

None of these projects I tested it with have GH releases. It looks like this is the cause of the problem, perhaps?

**Comment by alexmacarthur** [comment]
I have confirmed that this will run successfully, as long as I have at least one valid release published in GitHub. For the repo I shared above, that's here:

https://github.com/alexmacarthur/macarthur-me/releases/tag/v0.0.0

**Comment by calavera** [comment]
:thinking: that's a very weird behavior. I've tested it with this repository that doesn't have any tags: https://github.com/calavera/web-test2

Have you by any chance modified the dev plugin? Can you put in this thread the full stack trace that you get when this error happen?

**Comment by alexmacarthur** [comment]
@calavera You bet. Here's what I get after trying to run the tool without any tags on version 2.11.14:

```
Connected!
Waiting for localhost:34567.
Connected!
Waiting for localhost:8888.
Connected!
TypeError: Invalid Version: undefined
    at new SemVer (~/.nvm/versions/node/v10.15.3/lib/node_modules/netlify-cli/node_modules/semver/semver.js:305:11)
    at compare (~/.nvm/versions/node/v10.15.3/lib/node_modules/netlify-cli/node_modules/semver/semver.js:614:10)
    at Function.gt (~/.nvm/versions/node/v10.15.3/lib/node_modules/netlify-cli/node_modules/semver/semver.js:643:10)
    at ~/.nvm/versions/node/v10.15.3/lib/node_modules/netlify-cli/node_modules/gh-release-fetch/dist/index.js:32:25
    at Generator.next (<anonymous>)
    at fulfilled (~/.nvm/versions/node/v10.15.3/lib/node_modules/netlify-cli/node_modules/gh-release-fetch/dist/index.js:4:58)
```

**Comment by alexmacarthur** [comment]
I guess that particular error might have something to do with GitHub API limits. Traced it back to here: 

https://github.com/netlify/gh-release-fetch/blob/master/src/index.ts#L30

And when I hit the following URL directly, I get a rate limit error: 

https://api.github.com/repos/netlify/live-tunnel-client/releases/latest

```
{
  "message": "API rate limit exceeded for 198.52.26.32. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

**Comment by alexmacarthur** [comment]
Perhaps an alternative is to just fetch what's on the master branch when the latest version of the tool itself fails to successfully be fetched.
