### ISSUE TITLE
🐛 Cannot read property 'statusCode' of undefined

### ISSUE THREAD

**Issue by AryanJ-NYC** [netlify/netlify-dev-plugin#160]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
Error thrown:

```
TypeError: Cannot read property 'statusCode' of undefined
    at /Users/aryanjabbari/.nvm/versions/node/v10.14.1/lib/node_modules/netlify-cli/node_modules/netlify-dev-plugin/src/utils/serve-functions.js:35:32
    at /Users/aryanjabbari/.nvm/versions/node/v10.14.1/lib/node_modules/netlify-cli/node_modules/netlify-dev-plugin/src/utils/serve-functions.js:71:7
    at process._tickCallback (internal/process/next_tick.js:68:7)
TypeError: Cannot read property 'statusCode' of undefined
    at /Users/aryanjabbari/.nvm/versions/node/v10.14.1/lib/node_modules/netlify-cli/node_modules/netlify-dev-plugin/src/utils/serve-functions.js:35:32
    at /Users/aryanjabbari/.nvm/versions/node/v10.14.1/lib/node_modules/netlify-cli/node_modules/netlify-dev-plugin/src/utils/serve-functions.js:71:7
    at process._tickCallback (internal/process/next_tick.js:68:7)

/Users/aryanjabbari/.nvm/versions/node/v10.14.1/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:116
      throw ex;
      ^
abort({}) at Error
    at jsStackTrace (/Users/aryanjabbari/.nvm/versions/node/v10.14.1/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:1070:13)
    at stackTrace (/Users/aryanjabbari/.nvm/versions/node/v10.14.1/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:1087:12)
    at process.abort (/Users/aryanjabbari/.nvm/versions/node/v10.14.1/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:8415:44)
    at process.emit (events.js:182:13)
    at processEmit [as emit] (/Users/aryanjabbari/.nvm/versions/node/v10.14.1/lib/node_modules/netlify-cli/node_modules/signal-exit/index.js:155:32)
    at emitPromiseRejectionWarnings (internal/process/promises.js:119:20)
    at process._tickCallback (internal/process/next_tick.js:69:34)
```

**- If the current behavior is a bug, please provide the steps to reproduce.**
1) Clone https://github.com/AryanJ-NYC/reactandtypescript.dev
2) Edit `/functions/submitEmailAddress.js` to be:

```javascript
exports.handler = async function(_, __, callback) {
  return callback(null, {
    headers: {
      'Access-Control-Allow-Headers': '*',
      'Access-Control-Allow-Methods': 'OPTIONS,POST',
      'Access-Control-Allow-Origin': 'http://localhost:8000',
    },
    statusCode: 201,
    body: 'someBody',
  });
};
```

3) Go to http://localhost:8000/.
4) Submit a (faux?) email address.
5) Get error

**- What is the expected behavior?**
A lack of error.

**- Please mention your node.js, and operating system version.**
Node: v10.14.1 on MacOS 10.14.4

**Comment by sw-yx** [comment]
you're using `async` and callback together. when async is used, `callback` doesnt do anything. just return:

```js
exports.handler = async function() {
  return {
    headers: {
      'Access-Control-Allow-Headers': '*',
      'Access-Control-Allow-Methods': 'OPTIONS,POST',
      'Access-Control-Allow-Origin': 'http://localhost:8000',
    },
    statusCode: 201,
    body: 'someBody',
  }
};
```

**Comment by AryanJ-NYC** [comment]
🤦‍♂️ Thanks so much!
